###### bridge from ROS to MQTT ######

- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: vda5050_msgs.msg:State
  topic_from: /state
  topic_to: qa/<your_vehicle_id>/state
  
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: vda5050_msgs.msg:Visualization
  topic_from: /viz_to_mc
  topic_to: qa/<your_vehicle_id>/visualization

- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: vda5050_msgs.msg:Connection
  topic_from: /connection
  topic_to: qa/<your_vehicle_id>/connection
  
  ###### bridge from ROS to MQTT ######

- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: vda5050_msgs.msg:Action
  topic_from: qa/<your_vehicle_id>/instantActions
  topic_to: /instantActions
  
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: vda5050_msgs.msg:Order
  topic_from: qa/<your_vehicle_id>/order
  topic_to: /order_from_mc
